org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
android.useAndroidX=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a
newArchEnabled=true
hermesEnabled=true
edgeToEdgeEnabled=false


MYAPP_UPLOAD_STORE_FILE=key.keystore
MYAPP_UPLOAD_KEY_ALIAS=abhishek
MYAPP_UPLOAD_STORE_PASSWORD=Htmr$@3356
MYAPP_UPLOAD_KEY_PASSWORD=Htmr$@3356